AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Static Website hosting Using cloudformation'

Resources:
  MyS3Bucket: 
    Type: 'AWS::S3::Bucket'
    Properties: 
      BucketName: 'my-s3-static-bucket-by-cf-pk'
      WebsiteConfiguration:
        IndexDocument: 'index.html'
